(WIP) Add Expression.snippet
python setup.py build_ext --inplace
Compiling cygroonga.pyx because it changed.
Cythonizing cygroonga.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        close_tag_lengths = <unsigned int*>malloc(sizeof(unsigned int) *
n_tags)
        if close_tag_lengths == NULL:
            raise MemoryError()
        try:
            for i, (open_tag, close_tag) in enumerate(tag_pairs):
                open_tags[i] = open_tag.encode('UTF-8')
                                             ^
------------------------------------------------------------

cygroonga.pyx:675:46: Storing unsafe C derivative of temporary Python
reference

Error compiling Cython file:
------------------------------------------------------------
...
        if close_tag_lengths == NULL:
            raise MemoryError()
        try:
            for i, (open_tag, close_tag) in enumerate(tag_pairs):
                open_tags[i] = open_tag.encode('UTF-8')
                close_tags[i] = close_tag.encode('UTF-8')
                                               ^
------------------------------------------------------------

cygroonga.pyx:676:48: Storing unsafe C derivative of temporary Python
reference
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    libraries=["groonga"])
  File
"/Users/h-nakamura/.anyenv/envs/pyenv/versions/3.4.3/lib/python3.4/site-packages/Cython/Build/Dependencies.py",
line 865, in cythonize
    cythonize_one(*args[1:])
  File
"/Users/h-nakamura/.anyenv/envs/pyenv/versions/3.4.3/lib/python3.4/site-packages/Cython/Build/Dependencies.py",
line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cygroonga.pyx