Uncomment Database and I get a compile error again
python setup.py build_ext --inplace
Compiling cygroonga.pyx because it changed.
Cythonizing cygroonga.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        self._c_ctx = ccygroonga.grn_ctx_open(0)

    def db_create(self, path):
        c_path = path.encode('UTF-8')
        c_db = ccygroonga.grn_db_create(self._c_ctx, c_path, NULL)
        return Database(self._c_ctx, c_db)
                           ^
------------------------------------------------------------

cygroonga.pyx:23:28: Cannot convert 'grn_ctx *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        self._c_ctx = ccygroonga.grn_ctx_open(0)

    def db_create(self, path):
        c_path = path.encode('UTF-8')
        c_db = ccygroonga.grn_db_create(self._c_ctx, c_path, NULL)
        return Database(self._c_ctx, c_db)
                                        ^
------------------------------------------------------------

cygroonga.pyx:23:41: Cannot convert 'grn_obj *' to Python object
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    libraries=["groonga"])
  File
"/Users/hnakamur/.anyenv/envs/pyenv/versions/3.4.3/lib/python3.4/site-packages/Cython/Build/Dependencies.py",
line 865, in cythonize
    cythonize_one(*args[1:])
  File
"/Users/hnakamur/.anyenv/envs/pyenv/versions/3.4.3/lib/python3.4/site-packages/Cython/Build/Dependencies.py",
line 985, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cygroonga.pyx